<a href="https://colab.research.google.com/github/karna-charan/-Neural-Networks-and-Deep-Learning-/blob/main/ASSIGNMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.What is the syntax for creating a tensor.**

In [3]:
import torch
t = torch.tensor([10, 20, 30])
print(t)

tensor([10, 20, 30])


**3.Create a 2×3 tensor filled with zeros and another filled with ones.**

In [6]:
import tensorflow as tf
zeros_tensor = tf.zeros((2, 3))
ones_tensor = tf.ones((2, 3))
print("Zeros Tensor:\n", zeros_tensor)
print("Ones Tensor:\n", ones_tensor)


Zeros Tensor:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
Ones Tensor:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


**4.Convert a Python list [[1,2,3],[4,5,6]] into a tensor and print its shape and data type.**

In [7]:
import torch

# Python list
data = [[1, 2, 3], [4, 5, 6]]

# Convert to tensor
t = torch.tensor(data)

# Print shape and data type
print("Shape:", t.shape)
print("Data type:", t.dtype)


Shape: torch.Size([2, 3])
Data type: torch.int64


**5.Reshape a tensor of size 12 into shape (3,4).**

In [4]:
import torch

# Create a tensor with 12 elements
t = torch.arange(12)

# Reshape to (3, 4)
reshaped = t.reshape(3, 4)

print(reshaped)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


**6.Find the rank (number of dimensions) of a given tensor.**

In [5]:
import torch

# Example tensor
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# Find rank (number of dimensions)
rank = t.ndim   # or t.dim()

print("Rank:", rank)


Rank: 2


**7.Extract the second row and third column from a 2D tensor.**

In [8]:
import torch

# Example 2D tensor
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# Extract second row and third column
second_row = t[1]      # index 1 = second row
third_column = t[:, 2] # index 2 = third column

print("Second row:", second_row)
print("Third column:", third_column)


Second row: tensor([4, 5, 6])
Third column: tensor([3, 6])


**8.Compute matrix multiplication between tensors of shape (3,4) and (4,2).**

In [9]:
import torch

# Create tensors
A = torch.randn(3, 4)  # shape (3,4)
B = torch.randn(4, 2)  # shape (4,2)
# Matrix multiplication
C = torch.matmul(A, B)
print("Result:\n", C)
print("Shape:", C.shape)

Result:
 tensor([[ 1.2951, -1.8257],
        [-1.1264, -0.8605],
        [-0.8252, -0.4255]])
Shape: torch.Size([3, 2])


**9.Find the transpose of a 3D tensor**

In [10]:
  import torch

  # Example 3D tensor
  t = torch.tensor([[[1, 2],
                    [3, 4],
                    [5, 6]]])

  # Transpose (swap dimensions 1 and 2)
  t_transpose = t.transpose(1, 2)

  print("Original shape:", t.shape)
  print("Transposed shape:", t_transpose.shape)
  print(t_transpose)


Original shape: torch.Size([1, 3, 2])
Transposed shape: torch.Size([1, 2, 3])
tensor([[[1, 3, 5],
         [2, 4, 6]]])


**10.Implement softmax using tensor operations (no built-in function).**

In [11]:
import torch
# Example tensor
x = torch.tensor([1.0, 2.0, 3.0])
# Softmax (manual)
x_max = torch.max(x)                 # for numerical stability
exp_x = torch.exp(x - x_max)         # exponentiate
softmax = exp_x / torch.sum(exp_x)   # normalize
print("Softmax:", softmax)

Softmax: tensor([0.0900, 0.2447, 0.6652])


**11.Normalize a tensor so that values lie between 0 and 1.**

In [12]:
import torch
# Example tensor
t = torch.tensor([2.0, 5.0, 10.0, 20.0])
# Min-Max normalization to [0, 1]
t_min = t.min()
t_max = t.max()
normalized = (t - t_min) / (t_max - t_min)
print("Normalized tensor:", normalized)

Normalized tensor: tensor([0.0000, 0.1667, 0.4444, 1.0000])


**12.Write code to compute gradients of a tensor operation (PyTorch)**

In [13]:
import torch
# Create tensor with gradient tracking
x = torch.tensor(2.0, requires_grad=True)
# Tensor operation
y = x**2 + 3*x + 1   # y = x² + 3x + 1
# Compute gradients
y.backward()
# Print gradient dy/dx
print("Gradient:", x.grad)

Gradient: tensor(7.)


**13.Convert an image tensor (H, W, C) to (C, H, W).**

In [14]:
import torch
# Example image tensor with shape (H, W, C)
img = torch.randn(64, 64, 3)  # (H=64, W=64, C=3)
# Convert to (C, H, W)
img_chw = img.permute(2, 0, 1)
print("New shape:", img_chw.shape)

New shape: torch.Size([3, 64, 64])


**14.Mask elements in a tensor based on a condition.**

In [15]:
import torch
# Example tensor
t = torch.tensor([1, 5, 8, 2, 10])
# Mask elements greater than 5
mask = t > 5          # condition
masked = t[mask]      # apply mask
print("Mask:", mask)
print("Masked values:", masked)

Mask: tensor([False, False,  True, False,  True])
Masked values: tensor([ 8, 10])


**20.Implement cosine similarity using tensor operations.**

In [16]:
import torch
# Example tensors
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
# Cosine similarity
dot = torch.dot(a, b)
norm_a = torch.norm(a)
norm_b = torch.norm(b)
cos_sim = dot / (norm_a * norm_b)
print("Cosine Similarity:", cos_sim)

Cosine Similarity: tensor(0.9746)
